ci: fix integration test running with and without GSO (#4043)

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -37,10 +37,10 @@ jobs:
       - name: Run self tests, using QUIC v2
         if: success() || failure() # run this step even if the previous one failed
         run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -randomize-all -randomize-suites -trace integrationtests/self -- -version=2 ${{ env.QLOGFLAG }}
-      - name: Run set tests, with GSO enabled
-        if: success() || failure() # run this step even if the previous one failed
+      - name: Run self tests, with GSO disabled
+        if: ${{ matrix.os == 'ubuntu' && (success() || failure()) # run this step even if the previous one failed
         env:
-          QUIC_GO_ENABLE_GSO: true
+          QUIC_GO_DISABLE_GSO: true
         run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -randomize-all -randomize-suites -trace integrationtests/self -- -version=1 ${{ env.QLOGFLAG }}
       - name: Run tests (32 bit)
         if: ${{ matrix.os != 'macos' && (success() || failure()) }} # run this step even if the previous one failed
