ci: also run integration tests on Windows and macOS (#3987)

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -5,12 +5,18 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        os: [ "ubuntu" ]
         go: [ "1.20.x", "1.21.x" ]
-    runs-on: ${{ fromJSON(vars['INTEGRATION_RUNNER_UBUNTU'] || '"ubuntu-latest"') }}
+        include:
+          - os: "windows"
+            go: "1.21.x"
+          - os: "macos"
+            go: "1.21.x"
+    runs-on: ${{ fromJSON(vars[format('INTEGRATION_RUNNER_{0}', matrix.os)] || format('"{0}-latest"', matrix.os)) }}
     env:
       DEBUG: false # set this to true to export qlogs and save them as artifacts
       TIMESCALE_FACTOR: 3
-    name: Integration Tests (Go ${{ matrix.go }})
+    name: Integration Tests (${{ matrix.os }}, Go ${{ matrix.go }})
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-go@v3
@@ -37,7 +43,7 @@ jobs:
           QUIC_GO_ENABLE_GSO: true
         run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -randomize-all -randomize-suites -trace integrationtests/self -- -version=1 ${{ env.QLOGFLAG }}
       - name: Run tests (32 bit)
-        if: success() || failure() # run this step even if the previous one failed
+        if: ${{ matrix.os != 'macos' && (success() || failure()) }} # run this step even if the previous one failed
         env:
           GOARCH: 386
         run: |
