ci: use gcassert to check that quicvarint.Len is inlined (#5409)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -29,6 +29,9 @@ jobs:
         run: |
           cd integrationtests/gomodvendor
           go mod vendor
+      - name: run gcassert
+        if: success() || failure() # run this step even if the previous one failed
+        run: go tool gcassert ./...
   golangci-lint:
     runs-on: ubuntu-latest
     strategy:
