move FIPS integration tests to a separate Go module
The test spawns a new process to test interoberability between
FIPS and non-FIPS mode. This is now getting flagged by security
scanners.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -22,6 +22,10 @@ jobs:
       - name: Check that go.mod is tidied
         if: success() || failure() # run this step even if the previous one failed
         run: go mod tidy -diff
+      - name: Check that FIPS go.mod is tidied
+        if: success() || failure() # run this step even if the previous one failed
+        working-directory: integrationtests/fips
+        run: go mod tidy -diff
       - name: Run go fix
         if: success() || failure() # run this step even if the previous one failed
         run: go fix -diff ./...
