ci: combine the go generate workflow with the linting workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -9,7 +9,10 @@ jobs:
         with:
           skip-pkg-cache: true
           go-version: "1.20.x"
+      - name: Run code generators
+        run: .github/workflows/go-generate.sh
       - name: Check that no non-test files import Ginkgo or Gomega
+        if: success() || failure() # run this step even if the previous one failed
         run: .github/workflows/no_ginkgo.sh
       - name: Check for //go:build ignore in .go files
         run: |
@@ -19,6 +22,7 @@ jobs:
             exit 1
           fi
       - name: Check that go.mod is tidied
+        if: success() || failure() # run this step even if the previous one failed
         run: |
           cp go.mod go.mod.orig
           cp go.sum go.sum.orig
@@ -26,6 +30,7 @@ jobs:
           diff go.mod go.mod.orig
           diff go.sum go.sum.orig
       - name: Check that go mod vendor works
+        if: success() || failure() # run this step even if the previous one failed
         run: |
           cd integrationtests/gomodvendor
           go mod vendor
