ci: combine the go generate workflow with the linting workflow (#4053)
* ci: combine the go generate workflow with the linting workflow

* reorder

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -19,13 +19,18 @@ jobs:
             exit 1
           fi
       - name: Check that go.mod is tidied
+        if: success() || failure() # run this step even if the previous one failed
         run: |
           cp go.mod go.mod.orig
           cp go.sum go.sum.orig
           go mod tidy
           diff go.mod go.mod.orig
           diff go.sum go.sum.orig
+      - name: Run code generators
+        if: success() || failure() # run this step even if the previous one failed
+        run: .github/workflows/go-generate.sh
       - name: Check that go mod vendor works
+        if: success() || failure() # run this step even if the previous one failed
         run: |
           cd integrationtests/gomodvendor
           go mod vendor
